const tripTypes = [
  {
    id: "wildlife-safaris",
    title: "Wildlife Safaris",
    images: [
      "safari1.jpg",
      "safari2.jpg",
      "wildlife1.jpg",
      "wildlife2.jpg",
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    ],
    description: "See the Big Five and more in their natural habitat.",
    price: "KES 250,000",
    offer: "Private jeep upgrade",
  },
  {
    id: "honeymoon",
    title: "Honeymoon",
    images: [
      "./honeymoon2.jpg",
      "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&q=80",
      "./honeymoon2.png",
      "./honeymoon1.png",
    ],
    description: "Romantic getaways for newlyweds in breathtaking locations.",
    price: "KES 200,000",
    offer: "10% off for early bookings",
  },
  {
    id: "family",
    title: "Family",
    images: [
      "family2.jpg",
      "family3.jpg",
      "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Fun-filled adventures for the whole family.",
    price: "KES 180,000",
    offer: "Kids under 5 go free",
  },
  {
    id: "adventure",
    title: "Adventure",
    images: [
      "cultural1.jpg",
      "cultural3.jpg",
      "cultural2.png",
      "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Thrilling experiences for adrenaline seekers.",
    price: "KES 220,000",
    offer: "Includes free gear rental",
  },
  {
    id: "cultural-tours",
    title: "Cultural Tours",
    images: [
      "cultural1.jpg",
      "cultural3.jpg",
      "https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Immerse yourself in Kenya’s rich culture and heritage.",
    price: "KES 160,000",
    offer: "Guided by local experts",
  },
  {
    id: "eco-tours",
    title: "Eco-Tours",
    images: [
      "eco1.jpg",
      "eco2.png",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Sustainable travel for nature lovers.",
    price: "KES 140,000",
    offer: "Plant a tree with every booking",
  },
  {
    id: "luxury-vacations",
    title: "Luxury Vacations",
    images: ["luxury3.jpg", "luxury2.jpg", "luxury1.jpg", "honeymoon2.jpg"],
    description: "Indulge in 5-star comfort and exclusive experiences.",
    price: "KES 400,000",
    offer: "Complimentary spa treatment",
  },
  {
    id: "beach-holidays",
    title: "Beach Holidays",
    images: [
      "beach1.jpg",
      "beach2.jpg",
      "beach3.jpg",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Relax on Kenya’s stunning coastline.",
    price: "KES 170,000",
    offer: "Free snorkeling tour",
  },
  {
    id: "welness-retreats",
    title: "Wellness Retreats",
    images: [
      "wellness1.jpg",
      "wellness2.png",
      "wellness3.png",
      "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Rejuvenate your mind and body in serene settings.",
    price: "KES 210,000",
    offer: "Yoga sessions included",
  },
  {
    id: "culinary-tours",
    title: "Culinary Tours",
    images: [
      "culinary3.jpg",
      "culinary2.jpg",
      "culinary1.jpg",
      "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Taste the best of Kenyan and international cuisine.",
    price: "KES 190,000",
    offer: "Cooking class with local chefs",
  },
];

export default tripTypes;
